AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs18.x

  Sample SAM Template for lambda-nodejs18.x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ImageResize:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 10
      Environment:
        Variables:
          BUCKET_REGION:
          BUCKET_ACCESS_POINT:
          LOG_LEVEL:
          MIN_WIDTH:
          MAX_WIDTH:
          DEFAULT_WIDTH:
          MIN_HEIGHT:
          MAX_HEIGHT:
          DEFAULT_HEIGHT:
          DEFAULT_QUALITY:
          DEFAULT_TRANSFORM:
      CodeUri: src/
      Handler: index.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
